import type { Metadata } from "next";
import { Geist, Geist_Mono, Abyssinica_SIL } from "next/font/google";
import "./globals.css";
import Footer from "@/src/components/home/footer";
import { CartProvider } from "@/src/context/CartContext";
import { CategoryProvider } from "@/src/context/CategoryContext";
import Navbar from "@/src/components/home/navbar";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Backs the existing `font-serif` utility (see globals.css's --font-serif
// override) — matches the decorative headline font used in the Figma specs
// for WallPanel and Inspotlight card titles.
const abyssinicaSIL = Abyssinica_SIL({
  weight: "400",
  variable: "--font-abyssinica-sil",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${abyssinicaSIL.variable} h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning
      >
        <Providers>
          <CategoryProvider>
            <CartProvider>
              <Navbar />
              {children}
              <div className="hidden md:block">
                <Footer />
              </div>
            </CartProvider>
          </CategoryProvider>
        </Providers>
      </body>
    </html>
  );
}
